ktor:
    application:
        modules:
            - home.ApplicationKt.module
    deployment:
        port: $PORT
        shutdown:
            url: "/shutdown/"
    database:
        name: "$DB_NAME:"
        username: "$DB_USER:"
        password: "$DB_PASSWORD:"
        url: "$DB_URL:"
        port: "$DB_PORT"
        driver_postgres: "org.postgresql.Driver"
        driver_local: "org.h2.Driver"
        jdbcLocalURL: "jdbc:h2:file:./local.db"