apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: application-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: application-server
    spec:
      containers:
        - name: docker-server
          image: stanislavpoliakov/docker-server:1.3.3
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: config-application-server
                  key: application_port
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: config-application-server
                  key: database_name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets-application-server
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets-application-server
                  key: password
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /probe/liveness/
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /probe/readiness/
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 15
            failureThreshold: 5
