{
 "title": "Application-Server",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Latency(0.5)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, route) (rate(ktor_http_server_requests_seconds_bucket{route=~\"/nt-get.*\", status=\"200\"}[1m])))"
    }
   ]
  },
  {
   "title": "Latency(0.95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, route) (rate(ktor_http_server_requests_seconds_bucket{route=~\"/nt-get.*\", status=\"200\"}[1m])))"
    }
   ]
  },
  {
   "title": "Latency (0.99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, route) (rate(ktor_http_server_requests_seconds_bucket{route=~\"/nt-get.*\", status=\"200\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (1)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le, route) (rate(ktor_http_server_requests_seconds_bucket{route=~\"/nt-get.*\", status=\"200\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(status) (rate(ktor_http_server_requests_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by(route) (rate(ktor_http_server_requests_seconds_count{status!=\"200\"}[1m]))"
    }
   ]
  }
 ]
}