settings:
  main:
    namespace: namespace-application-server
    port: 8000
  deployment:
    replicas: 3
    update:
      strategy: RollingUpdate
      maxSurge: 1
      maxUnavailable: 0
    container:
      name: docker-server
      image: stanislavpoliakov/docker-server
  secrets:
    type: kubernetes.io/basic-auth
  service:
    protocol: TCP
    port: 80
    nodePort: 32761
    type: NodePort
  ingress:
    host: arch.homework
    path: /otusapp/stanislav_poliakov/(.*)
    pathType: Prefix
    port: 80

labels:
  application: application-server

global:
  postgresql:
    auth:
      database: database_application_server
      username: database_user
      password: database_password
    servicePort: 5432

postgresql:
  metadata:
    namespace: namespace-application-server

ingress-nginx:
  metadata:
    namespace: namespace-application-server