apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-{{ .Release.Name }}
  namespace: {{ .Values.settings.main.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.settings.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    type: {{ .Values.settings.deployment.update.strategy }}
    rollingUpdate:
      maxSurge: {{ .Values.settings.deployment.update.maxSurge }}
      maxUnavailable: {{ .Values.settings.deployment.update.maxUnavailable }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.settings.deployment.container.name }}
          image: {{ cat .Values.settings.deployment.container.image ":" .Chart.AppVersion | nospace }}
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: config-{{ .Release.Name }}
                  key: application_port
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: config-{{ .Release.Name }}
                  key: database_name
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: config-{{ .Release.Name }}
                  key: database_url
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: config-{{ .Release.Name }}
                  key: database_port
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: credentials-{{ .Release.Name }}
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials-{{ .Release.Name }}
                  key: password
          ports:
            - containerPort: {{ .Values.settings.main.port }}
          livenessProbe:
            httpGet:
              path: /probe/liveness/
              port: {{ .Values.settings.main.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /probe/readiness/
              port: {{ .Values.settings.main.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5
