apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ .Release.Name }}
  namespace: {{ .Values.settings.main.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: {{ .Values.settings.ingress.host }}
      http:
        paths:
          - path: {{ .Values.settings.ingress.path }}
            pathType: {{ .Values.settings.ingress.pathType }}
            backend:
              service:
                name: service-{{ .Release.Name }}
                port:
                  number: {{ .Values.settings.ingress.port }}
  ingressClassName: nginx