apiVersion: v1
kind: Secret
metadata:
  name: credentials-{{ .Release.Name }}
  namespace: {{ .Values.settings.main.namespace }}
  {{- template "application-service.labels" }}
  {{- template "application-service.annotations" }}
type: {{ .Values.settings.secrets.type }}
stringData:
  username: {{ .Values.global.postgresql.auth.username | b64enc | quote }}
  password: {{ .Values.global.postgresql.auth.password | b64enc | quote }}