apiVersion: v1
kind: Service
metadata:
  name: service-{{ .Release.Name }}
  namespace: {{ .Values.settings.main.namespace }}
  {{- template "application-service.labels" }}
  {{- template "application-service.annotations" }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: {{ .Values.settings.service.protocol }}
      port: {{ .Values.settings.service.port }}
      targetPort: {{ .Values.settings.main.port }}
      nodePort: {{ .Values.settings.service.nodePort }}
  type: {{ .Values.settings.service.type }}