apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-service-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    release: application-server
spec:
  namespaceSelector:
    matchNames:
      - "{{ $.Release.Namespace }}"
  selector:
    matchLabels:
      app: application-server
  endpoints:
    - port: metrics
      interval: 15s
      honorLabels: true
      scheme: http